##### Import NumPy

In [1]:
import numpy as np

##### Creating 1D,2D,3D arrays and performing basic functions

In [3]:
#Creating a 1D array
a = np.array([1,2,3,4])
print("The Array : ",a)
print("The Dimension of a : ",a.ndim)
print("The Shape of a : ",a.shape)
print("The Data Type of a : ",a.dtype)
print("The itemsize : ",a.itemsize)
print("The size of the array : ",a.size)
print("The bytes of array : ",a.nbytes)

The Array :  [1 2 3 4]
The Dimension of a :  1
The Shape of a :  (4,)
The Data Type of a :  int32
The itemsize :  4
The size of the array :  4
The bytes of array :  16


In [33]:
#Creating a 2D array
b = np.array([[1,2,3,4],[5,6,7,8]],dtype="int16")
print("The Array : ",b)
print("The Dimension of b : ",b.ndim)
print("The Shape of b : ",b.shape)
print("The Data Type of b : ",b.dtype)
print("The itemsize : ",b.itemsize)
print("The size of the array : ",b.size)
print("The bytes of array : ",b.nbytes)

The Array :  [[1 2 3 4]
 [5 6 7 8]]
The Dimension of b :  2
The Shape of b :  (2, 4)
The Data Type of b :  int16
The itemsize :  2
The size of the array :  8
The bytes of array :  16


In [34]:
#Creating a 3D array
c = np.array([[[1,2,3,4],[5,6,7,8]],[[8,7,6,5],[4,3,2,1]]])
print("The Array : ",c)
print("The Dimension of c : ",c.ndim)
print("The Shape of c : ",c.shape)
print("The Data Type of c : ",c.dtype)
print("The itemsize : ",c.itemsize)
print("The size of the array : ",c.size)
print("The bytes of array : ",c.nbytes)

The Array :  [[[1 2 3 4]
  [5 6 7 8]]

 [[8 7 6 5]
  [4 3 2 1]]]
The Dimension of c :  3
The Shape of c :  (2, 2, 4)
The Data Type of c :  int32
The itemsize :  4
The size of the array :  16
The bytes of array :  64


##### Workout Problems

In [35]:
result = np.zeros((5,5))
result

one = np.ones((3,3))
one

one[1,1] = 9
one

result[1:-1,1:-1] = one
result

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 9., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
#Memory Consumption
arr = np.zeros((3,4))
print(arr)
memory = arr.nbytes
print("The Memory Consumption of the array : ",memory)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
The Memory Consumption of the array :  96


In [37]:
#Reshape and Dimension
arr2 = np.ones((2,5))
print("Original Array :\n",arr2)
reshaped_arr2 = np.reshape(arr2,(5,2))
print("Reshaped Array : \n",reshaped_arr2)

Original Array :
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Reshaped Array : 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [38]:
#Array with Random Data 

#Standard Normal Distribution
random_array1 = np.random.normal(0,1,size=(3,3))
print("Random array from Standard Normal Distribution:")
print(random_array1)

#Random Values
random_array2 = np.random.rand(3,3)
print("Random array from interval(0,1): ")
print(random_array2)

#Random Integers
random_array3 = np.random.randint(0,10,size = (5,5))
print("Random array from integers: ")
print(random_array3)


Random array from Standard Normal Distribution:
[[-0.10185451  2.16839393  1.45909459]
 [ 0.05809098  0.80218878 -0.20523954]
 [ 0.84894806  0.89240041  0.62035379]]
Random array from interval(0,1): 
[[0.11672586 0.06318775 0.57704457]
 [0.4946289  0.93301483 0.40570249]
 [0.98357855 0.72733901 0.16913184]]
Random array from integers: 
[[6 5 4 3 5]
 [1 6 5 6 9]
 [1 3 0 9 7]
 [8 5 7 1 8]
 [5 2 5 4 8]]


In [39]:
#Creating Full Array
arr3 = np.full((4,4),23)
print("Full Array: \n",arr3)

Full Array: 
 [[23 23 23 23]
 [23 23 23 23]
 [23 23 23 23]
 [23 23 23 23]]


In [40]:
#Operations with Ones and Zeros
array_1 = np.zeros((3,3))
array_2 = np.ones((3,3))
result = np.add(array_1 , array_2)
print(result)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [68]:
#1D array with range 1 to 10
a = np.arange(1,10)
print(a)

#3x3 zero array 
b = np.zeros((3,3))
print(b)

#2x3 array with float 1.2
c = np.full((2,3),1.2)
print(c)

#array with random integers
d = np.random.randint(1,10,size = 5)
print(d)

#array of even spaced integers
e = np.arange(1,5.5,0.5)
print(e)

#reshaping 1D array into 2D
f = np.array([0,1,2,3,4,5])
reshaped_f = f.reshape((2,3))
print(reshaped_f)

#accessing elements
g = np.array([1,2,3,4,5])
h = np.array([[1,2,3,4],[5,6,7,8]])
print("Third element of 1D array: ",g[2])
print("Last element of 1D array: ",g[len(g)-1])
print("First column of 2D array: ",h[:,0])
print("Second row of 2D array: ",h[1,:])

#sum and mean of 1D array
i = np.array([1,2,3,4,5])
print("The sum of the array: ",np.sum(i))
print("The mean of the array: ",np.mean(i))

#element-wise and dot product of 2 1D arrays
j = np.array([1,2,3,4])
k = np.array([5,6,7,8])
product = j*k
print("The product of two 1D arrays: ",product)
dot_product = np.dot(j,k)
print("The dot product of two arrays: ",dot_product)

#max value and its index in 1D array
l = np.array([10,20,30,40,50,24,43])
m = np.max(l)
n = np.argmax(l)
print("The maximum value of the array: ",m)
print("Index of the maximum value: ",n)



[1 2 3 4 5 6 7 8 9]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1.2 1.2 1.2]
 [1.2 1.2 1.2]]
[6 3 8 3 3]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
[[0 1 2]
 [3 4 5]]
Third element of 1D array:  3
Last element of 1D array:  5
First column of 2D array:  [1 5]
Second row of 2D array:  [5 6 7 8]
The sum of the array:  15
The mean of the array:  3.0
The product of two 1D arrays:  [ 5 12 21 32]
The dot product of two arrays:  70
The maximum value of the array:  50
Index of the maximum value:  4


##### Copy and View

In [72]:
#copy and view
arr = np.array([1,2,3,4,5])

x = arr.copy()
y = arr.view()

x[0] = 11
y[4] = 55


print(x.base)
print(y.base)

print(arr,x,y)

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

None
[ 1  2  3  4 55]
[ 1  2  3  4 55] [11  2  3  4  5] [ 1  2  3  4 55]
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)
